name: Deploy dist

on:
  push:
    branches: ['main']
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets the GITHUB_TOKEN permissions
permissions:
  contents: write

# Allow one concurrent deployment
concurrency:
  group: 'release'
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          persist-credentials: false
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Checkout dist
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true
          path: './dist'
          ref: dist
      - name: Build
        working-directory: '.'
        run: pnpm build
      - name: Push dist changes
        working-directory: dist
        run: |
          git config --global user.name "actions-bot"
          git config --global user.email "actions-bot@users.noreply.github.com"
          git add .
          git commit -m "v01.$(date +%Y%m%d)"
          git push
